language: node_js

node_js:
  - "4"
  - "6"

before_install:
  - npm install -g npm

script:
  - npm run lint
#  - npm run test

notifications:
#  irc: "irc.freenode.org#deltion" # Cuz retards gonna retard..
